# Desktop setup: ComfyUI LAN + laptop config template
#   .\scripts\remote-laptop\setup_desktop_for_laptop_jan.ps1
# SMB admin: .\scripts\remote-laptop\setup_shared_images_elevated.cmd

$ErrorActionPreference = "Stop"
. (Join-Path $PSScriptRoot "_config.ps1")

function Test-IsAdmin {
    $p = New-Object Security.Principal.WindowsPrincipal([Security.Principal.WindowsIdentity]::GetCurrent())
    return $p.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
}

$IsAdmin = Test-IsAdmin
$SmRoot = Get-StabilityMatrixRoot
$SmSettings = Join-Path $SmRoot "Data\settings.json"
$DeliveryPath = Get-DesktopDeliveryPath
$ShareName = "StudioBata"
$ComfyPort = 8188
$DesktopIp = Get-DesktopLanIp
if (-not $DesktopIp) { Write-Warning "Could not detect LAN IP" }

Write-Host "=== Remote laptop — desktop setup ===" -ForegroundColor Cyan
Write-Host "LAN IP: $DesktopIp  Share: \\$env:COMPUTERNAME\$ShareName"

if (-not $DeliveryPath) {
    Write-Warning "outputs.delivery not set in stability-studio-mcp/config.yaml"
} elseif (-not (Test-Path $DeliveryPath)) {
    New-Item -ItemType Directory -Path $DeliveryPath -Force | Out-Null
}

if (Test-Path $SmSettings) {
    Write-Host "[OK] Run install_comfyui_lan_launcher.ps1 if ComfyUI is not on 0.0.0.0:8188" -ForegroundColor Yellow
}

if (-not $IsAdmin) {
    Write-Host "[!!] Run setup_shared_images_elevated.cmd as Administrator for SMB." -ForegroundColor Yellow
} else {
    & (Join-Path $PSScriptRoot "setup_shared_images_elevated.ps1")
}

$LaptopDir = Join-Path $RemoteLaptopRepoRoot "config-examples\laptop-remote"
$laptopConfig = @"
# Generated by setup_desktop_for_laptop_jan.ps1 — copy to laptop stability-studio-mcp/config.yaml
# Desktop: $env:COMPUTERNAME @ $DesktopIp

stability_matrix:
  root: "$($SmRoot.Replace('\','/'))"
  data: "$($SmRoot.Replace('\','/'))/Data"
  models: "$($SmRoot.Replace('\','/'))/Data/Models"
  workflows: "$($SmRoot.Replace('\','/'))/Data/Workflows"
  packages:
    comfyui: "$($SmRoot.Replace('\','/'))/Data/Packages/ComfyUI"

outputs:
  delivery: "Z:/"

comfyui:
  url: "http://${DesktopIp}:$ComfyPort"
  timeout_seconds: 600

invokeai:
  enabled: false

default_backend: comfyui
default_content_rating: open
default_style: juggernaut

hardware:
  vram_gb: 0
  gpu_only: true
  prefer_prompt_quality: true

catalog_file: "catalog.yaml"

gpu_backend:
  enforce_exclusive: false
"@
$outPath = Join-Path $LaptopDir "config.generated.yaml"
Set-Content $outPath $laptopConfig -Encoding UTF8
Write-Host "[OK] Wrote $outPath (copy to laptop after mapping Z:)" -ForegroundColor Green
